### ISSUE TITLE
Multiline-footnotes should work when the first line is empty.

### ISSUE THREAD

**Issue by Eyas** [remarkjs/remark-footnotes#1] opened 2020-05-02 19:43 UTC
### Subject of the issue

Prettier 2.0.0 reformats markdown so that:

```
[^1]: Some very long line that goes on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on
```

becomes:

```
[^1]:
  Some very long line that goes on and on and on and on and on and on and on and
  on and on and on and on and on and on and on and on and on and on and on and
  on and on and on and on and on and on and on and on and on and on and on
```

rather than a first line + a continuation.

**But remark-footnotes fails to correctly parse mutliline footnotes.** 

### Your environment

*   **OS**: Windows
*   **Packages**: remark-footnotes@1.0.0
*   **Env**: npm

### Steps to reproduce

Use this MD or MDX:

```
Hey there [^1]

[^1]:
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
  nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
  eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt
  in culpa qui officia deserunt mollit anim id est laborum.
```

### Expected behaviour

AST should look like this:

```
root
  children
    paragraph
    footnoteDefinition
      paragraph
```

### Actual behaviour

AST looks like this:

```
root
  children
    paragraph
    footnoteDefinition  # (empty)
    paragraph
```

**Comment by wooorm** [comment] 2020-05-02 20:29
Do you find 4 spaces of indentation instead of 2 an acceptable solution? Because that works currently.

**Comment by Eyas** [comment] 2020-05-02 21:02
Interesting. This is a good workaround. Configuring prettier tabWidth to 4 causes it to get to 4 spaces.

I'm curious if there's there a proper spec here? Two spaces us usually enough for list continuation, right? If two spaces is definitely wrong, I'll close this in favor of a prettier bug.

**Comment by wooorm** [comment] 2020-05-02 21:13
There is no spec. Before, this was based on a now not frequently used markdown flavour. I now based on on pandoc, but a bit stricter. Pandoc doesn’t need any indentation 🤨 it’s in fact very lazy and hard to reason about, so instead I decided to go with 4 spaces (similar to code blocks)

While lists sometimes require 2 (or 3, if numbered), in my experience the safest is always 4: it works the same in every markdown flavour. Otherwise it get real messy real fast

**Comment by wooorm** [comment] 2020-05-19 19:42
Alright, closing this because I don’t know what there could be implemented. Feel free to comment if there is something you’d wish was implemented.

**Closed as completed by wooorm** 2020-05-19 19:42 UTC
Labels: 🙋 no/question

**Comment by thorn0** [comment] 2020-05-29 21:18
This blocks Prettier from updating to newest remark. I guess it's fine to always output 4 spaces for footnotes when formatting, but the problem is with parsing. Prettier wouldn't be able to parse its own earlier output with footnotes indented with less than 4 spaces. What is the harm if this gets allowed? Are there some horrible ambiguities that you're trying to avoid this way?

**Comment by wooorm** [comment] 2020-05-30 08:01
Nowhere in Markdown are two spaces used. Nowhere is it configurable how many spaces can start an indented code block.
Pandoc behavior, which this project follows a bit (but is buggy too, and from before commonmark), [needs 4](https://pandoc.org/try/?text=asd%5B%5E1%5D%0A%0A%5B%5E1%5D%3A%0A++fgh%0A%0A++jkl%0A%0A&from=markdown&to=html4&standalone=0). Same with PHP Markdown Extra (also ancient), which we used to somewhat follow (but is more obsolete now), [also documents needing 4](https://michelf.ca/projects/php-markdown/extra/#footnotes).

> What is the harm if this gets allowed? 

There is no good rule for the following:

```
[x]: -

    4

   3

  2

 1

0
```

This becomes much more complex when combining with other containers (lists, block quotes, list items). Parsing 2 spaces might help Prettier but might just as well break others. The problem here is that footnotes are an unspecified extension. There is no standard.

**Comment by thorn0** [comment] 2020-05-30 11:11
Okay. I think it'll be enough for Prettier to add a disclaimer to the docs that support for non-standard syntax is best effort.

**Comment by wooorm** [comment] 2020-05-31 09:31
👍 I hope that [CMSM](https://github.com/micromark/common-markup-state-machine) will be a more formal version of CM, as it describes how to parse constructs. Maybe that could be used to specify common extensions like frontmatter as well. Maybe footnotes too, but the problem with footnotes is that there really is no good reference implementation. GFM has GH, frontmatter has Jekyll, etc. 🤔
